when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
           only_exceptions: false
           collect_serializer_data: false   # Désactiver la collecte des données de sérialisation
           collect_session_data: false     # Désactiver la collecte des données de session
           collect_request_data: false     # Désactiver la collecte des données des requêtes
           collect_db_data: false  
