services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sortir
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony_network

  # Application Symfony avec PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sortir
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      # - ./var/log:/var/www/html/var/log
      # - ./var/cache:/var/www/html/var/cache
    environment:
      - APP_ENV=dev
      - PHP_SESSION_PATH=/var/www/html/var/sessions
    depends_on:
      - postgres
    networks:
      - symfony_network

  # Serveur web Nginx
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  # Serveur de développement Vite
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: symfony_vite
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - symfony_network

  # PGAdmin pour la gestion de la base de données
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: symfony_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8181:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - symfony_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  symfony_network:
    driver: bridge